import XCTest

@testable import ManifoldInference

/// Byte-exact golden tests for the embedded-Jinja chat-template render path (#1938).
///
/// Unlike ``JinjaPromptRendererTests`` — which asserts `rendered.contains(...)`
/// against synthetic templates and so cannot catch whitespace / special-token
/// drift — these tests assert the renderer's output is **byte-for-byte equal** to
/// the output Hugging Face `transformers` produces for the same template and
/// context. The goldens are committed under `Fixtures/ChatTemplates/` and
/// regenerated by `regenerate.py` (which reproduces transformers'
/// `_compile_jinja_template` Jinja environment — no model download). This locks
/// in the #1909 tool-threading fix and turns any future swift-jinja / context
/// regression into a CI failure instead of a one-model-at-a-time bug report.
///
/// The fixture *inputs* are built in Swift here; the `.context.json` beside each
/// template mirrors them for the generator. If the two drift, the golden stops
/// matching swift-jinja's output and the byte-match fails — so the JSON and the
/// Swift inputs are kept honest by the test itself.
final class ChatTemplateGoldenTests: XCTestCase {

    // MARK: - Fixture loading

    private func fixture(_ name: String, ext: String) throws -> String {
        let url = try XCTUnwrap(
            Bundle.module.url(
                forResource: name,
                withExtension: ext,
                subdirectory: "ChatTemplates"
            ),
            "missing fixture \(name).\(ext) — is Fixtures/ChatTemplates copied into the test bundle?"
        )
        return try String(contentsOf: url, encoding: .utf8)
    }

    /// Renders `messages` through the embedded-Jinja path for fixture `name` and
    /// asserts the output byte-matches `name.golden.txt`.
    private func assertGolden(
        _ name: String,
        template templateFile: String? = nil,
        systemPrompt: String?,
        messages: [StructuredMessage],
        tools: [ToolDefinition] = [],
        documents: [RetrievedDocument] = [],
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws {
        let template = try fixture(templateFile ?? name, ext: "jinja")
        let golden = try fixture("\(name).golden", ext: "txt")
        let rendered = try XCTUnwrap(
            JinjaPromptRenderer.render(
                rawTemplate: template,
                messages: messages,
                systemPrompt: systemPrompt,
                tools: tools,
                documents: documents
            ),
            "swift-jinja failed to render \(name).jinja",
            file: file,
            line: line
        )
        XCTAssertEqual(
            rendered,
            golden,
            "\(name): rendered prompt does not byte-match the transformers golden. "
                + "If swift-jinja output legitimately changed, rerun regenerate.py and review the diff.",
            file: file,
            line: line
        )
    }

    // MARK: - Goldens (must byte-match transformers)

    func test_qwen25_withHostSystemPrompt() throws {
        try assertGolden(
            "qwen25",
            systemPrompt: "You are a helpful coding assistant.",
            messages: [StructuredMessage(role: "user", content: "What is 2+2?")]
        )
    }

    func test_qwen25_injectsDefaultSystemTurn() throws {
        try assertGolden(
            "qwen25_default_system",
            template: "qwen25",
            systemPrompt: nil,
            messages: [StructuredMessage(role: "user", content: "Hi")]
        )
    }

    func test_llama32_knowledgeDatePreamble() throws {
        try assertGolden(
            "llama32",
            systemPrompt: nil,
            messages: [StructuredMessage(role: "user", content: "Hi")]
        )
    }

    func test_nativeTool_threadsToolsCallsAndResults() throws {
        let call = ToolCall(id: "call_1", toolName: "get_weather", arguments: #"{"city":"Paris"}"#)
        try assertGolden(
            "native_tool",
            systemPrompt: nil,
            messages: [
                StructuredMessage(role: "user", content: "weather in Paris?"),
                StructuredMessage(role: "assistant", parts: [.toolCall(call)]),
                StructuredMessage(
                    role: "tool",
                    parts: [.toolResult(ToolResult(callId: "call_1", content: "18C and sunny"))]
                ),
            ],
            tools: [Self.weatherTool()]
        )
    }

    /// #1967: a vision template's image-placeholder branch fires when an image
    /// part is threaded into the per-message `content` list. Before #1967 the
    /// renderer dropped every `.image` part, so the `<|vision_start|>…` block
    /// never rendered. The golden is the transformers reference for the same
    /// content-list context the renderer now builds.
    func test_qwen2vl_threadsImagePlaceholder() throws {
        // Mirrors qwen2vl.context.json: a one-pixel PNG payload — the bytes are
        // irrelevant to the placeholder, only that an `.image` part is present.
        let imageData = try XCTUnwrap(Data(base64Encoded: "iVBORw0KGgo="))
        try assertGolden(
            "qwen2vl",
            systemPrompt: nil,
            messages: [
                StructuredMessage(
                    role: "user",
                    parts: [
                        .text("What is in this image?"),
                        .image(data: imageData, mimeType: "image/png"),
                    ]
                )
            ]
        )
    }

    /// #1967: a RAG grounding template's `{% if documents %}` block fires when
    /// retrieved passages are threaded into the `documents` context variable.
    /// Before #1967 `documents` was hard-coded `[]`, so the block was always
    /// falsey and retrieved chunks never reached a template that wanted them.
    func test_ragDocuments_threadsDocumentsBlock() throws {
        try assertGolden(
            "rag_documents",
            systemPrompt: nil,
            messages: [StructuredMessage(role: "user", content: "What is the capital of France?")],
            documents: [
                RetrievedDocument(title: "France", text: "Paris is the capital and most populous city of France."),
                RetrievedDocument(title: "Geography", text: "France is a country in Western Europe."),
            ]
        )
    }

    // MARK: - Sabotage guard

    /// Proves the byte-match is exact, not a `contains`-style false pass: a
    /// single-token perturbation of the golden must make the comparison fail.
    /// (Kept as a live assertion — it inverts `XCTAssertEqual`, so it does not
    /// itself depend on the production code breaking.)
    func test_sabotage_singleTokenPerturbationFailsByteMatch() throws {
        let template = try fixture("qwen25", ext: "jinja")
        let golden = try fixture("qwen25.golden", ext: "txt")
        let rendered = try XCTUnwrap(
            JinjaPromptRenderer.render(
                rawTemplate: template,
                messages: [StructuredMessage(role: "user", content: "What is 2+2?")],
                systemPrompt: "You are a helpful coding assistant.",
                tools: []
            )
        )
        let perturbed = golden.replacingOccurrences(of: "<|im_start|>", with: "<|im_begin|>")
        XCTAssertNotEqual(rendered, perturbed, "a perturbed golden must not byte-match — guards against a contains-style false pass")
    }

    // MARK: - Fixtures

    private static func weatherTool() -> ToolDefinition {
        ToolDefinition(
            name: "get_weather",
            description: "Look up the weather for a city",
            parameters: .object([
                "type": .string("object"),
                "properties": .object([
                    "city": .object(["type": .string("string")])
                ]),
                "required": .array([.string("city")]),
            ])
        )
    }
}
