import Foundation

/// Builds a system-prompt preamble that nudges a model toward actually calling
/// its tools when one applies.
///
/// ## Why this exists
///
/// AI-product testing of ManifoldKit's tool-calling pipeline surfaced a
/// consistent failure mode: without an explicit preamble shaping tool
/// preference, `llama3.1:8b` invoked the right tool on roughly **50%** of
/// prompts that should have triggered a tool (e.g. "what time is it?" with
/// a `get_current_time` tool registered). The same run with the
/// ``Style/standard`` preamble below lifts that hit rate to **70–85%** —
/// a range tracking the variance between model snapshots and temperature
/// settings, but always materially higher than the no-preamble baseline.
///
/// The preamble is boring boilerplate that every consumer application ends
/// up writing anyway, and many write it slightly wrong in ways that suppress
/// tool calls further ("use tools when appropriate" is weaker than "you MUST
/// call the tool"). Centralising the known-good phrasing here means an app
/// that registers tools gets good tool recall by default.
///
/// ## Usage
/// ```swift
/// let tools: [ToolDefinition] = [weatherTool, clockTool]
/// let preamble = ToolSystemPromptBuilder.preferTools(for: tools)
/// let systemPrompt = preamble + "\n\n" + appSpecificSystemPrompt
/// ```
///
/// ## Preset selection
///
/// - ``Style/standard`` — default. Lists tools and instructs the model to
///   invoke them rather than guessing values a tool could provide.
/// - ``Style/strict`` — ``standard`` plus a "say 'I don't have a tool for
///   that' rather than guessing" clause. Use when hallucinated answers are
///   costlier than a terse refusal (e.g. agent workflows that branch on
///   tool output).
/// - ``Style/minimal`` — the tool list only, no imperative phrasing. For
///   apps that write their own preamble and just want the canonical tool
///   enumeration.
public struct ToolSystemPromptBuilder: Sendable {

    /// Tone of the preamble generated by ``preferTools(for:style:)``.
    public enum Style: Sendable, Equatable, Hashable {
        /// Default — lists tools and instructs the model to prefer them over
        /// guessing values a tool could provide.
        case standard
        /// ``standard`` plus a "say 'I don't have a tool for that' rather
        /// than guessing" clause. Use when hallucinated answers are costlier
        /// than a terse refusal.
        case strict
        /// Tool enumeration only, no imperative phrasing. For apps that
        /// write their own preamble.
        case minimal
    }

    /// Builds a system-prompt preamble that shapes tool-preference behaviour.
    ///
    /// - Parameters:
    ///   - definitions: Tools being made available to the model this turn.
    ///   - style: Tone of the preamble. See ``Style``. Defaults to
    ///     ``Style/standard``.
    /// - Returns: A newline-terminated preamble ready to concatenate with an
    ///   app-specific system prompt, or an empty string when `definitions`
    ///   is empty (a no-op preamble — safe to concatenate verbatim).
    public static func preferTools(
        for definitions: [ToolDefinition],
        style: Style = .standard
    ) -> String {
        // Empty tools list: emit nothing so consumers can `preamble +
        // appPrompt` unconditionally without worrying about a stray
        // "You have no tools." clause poisoning behaviour.
        guard !definitions.isEmpty else {
            return ""
        }

        let listing = definitions.map(renderTool(_:)).joined(separator: "\n")

        switch style {
        case .minimal:
            return "Available tools:\n\(listing)\n"

        case .standard:
            return """
                You have the following tools available:

                \(listing)

                When a tool can answer a question, you MUST call the tool. \
                Never guess values (timestamps, math, files, external data) \
                that a tool can provide. \(toolCallFormatInstruction)

                """

        case .strict:
            return """
                You have the following tools available:

                \(listing)

                When a tool can answer a question, you MUST call the tool. \
                Never guess values (timestamps, math, files, external data) \
                that a tool can provide. \(toolCallFormatInstruction)

                If no tool matches the user's request, say "I don't have a \
                tool for that" rather than guessing.

                """
        }
    }

    // MARK: - Tool-call format

    /// Concrete tool-call emission format folded into the imperative presets.
    ///
    /// ## Why a literal JSON envelope
    ///
    /// Templates that don't render tools natively (Phi-3.5, Mistral-7B-Instruct
    /// GGUFs, and every non-`gemma4` enum template) reach the model through this
    /// preamble alone — the model is told tools exist but, with only a vague
    /// "emit a tool_call" nudge, improvises an unparseable shape such as the
    /// Pythonic `tool_call(calc, "7823 * 41")` (positional, opaque) that no local
    /// parser can dispatch (#2002). Spelling out the exact `{"name": …,
    /// "arguments": {…}}` envelope — the shape the local `<tool_call>` /
    /// bare-`{"name"` dialects already consume — plus the named-argument
    /// requirement and an explicit "not a Python-style call" prohibition closes
    /// that gap. Native-tool templates never see this string: `GenerationQueue`'s
    /// fold decision skips the preamble entirely when the renderer emits tools
    /// natively (keyed on ``PromptRenderer/rendersToolsNatively``).
    private static let toolCallFormatInstruction = """
        To call a tool, respond with a single JSON object of exactly this \
        form and nothing else:

        {"name": "<one of the tool names above>", "arguments": {"<argument name>": <value>}}

        Use the argument names listed for the chosen tool. Do not write the \
        call as prose or as a Python-style function call such as `tool(value)`.
        """

    // MARK: - Rendering

    /// Renders a single tool definition as one line of the preamble tool list.
    ///
    /// Shape: `- <name>: <description> (arguments: a, b) (requires: a)`. Either
    /// parenthesised clause is dropped when empty, so a tool with no declared
    /// parameters renders as the bare `- <name>: <description>`. The `arguments`
    /// clause names every parameter the tool accepts — the JSON keys the model
    /// must use inside the `"arguments"` object (#2002) — while `requires` marks
    /// the mandatory subset. Tool names are emitted verbatim; consumers with
    /// exotic characters in names are responsible for the consequences.
    private static func renderTool(_ tool: ToolDefinition) -> String {
        let arguments = extractArgumentNames(from: tool.parameters)
        let required = extractRequiredArgumentNames(from: tool.parameters)
        var line = "- \(tool.name): \(tool.description)"
        if !arguments.isEmpty {
            line += " (arguments: \(arguments.joined(separator: ", ")))"
        }
        if !required.isEmpty {
            line += " (requires: \(required.joined(separator: ", ")))"
        }
        return line
    }

    /// Names every parameter the tool accepts, in a deterministic order.
    ///
    /// `properties` is an unordered JSON-Schema object (a Swift dictionary), so a
    /// raw key walk would emit a non-stable order across runs. To keep the
    /// preamble byte-stable, required arguments lead in schema-declared order
    /// (the array preserves it) and any remaining optional properties follow
    /// alphabetically. Returns `[]` when the schema declares no `properties`
    /// block — falling back to `required` alone is intentional, since some
    /// hand-built schemas list `required` without a matching `properties` map.
    private static func extractArgumentNames(
        from parameters: JSONSchemaValue
    ) -> [String] {
        let required = extractRequiredArgumentNames(from: parameters)
        guard case .object(let fields) = parameters,
              case .object(let properties) = fields["properties"] else {
            return required
        }
        let requiredSet = Set(required)
        let optional = properties.keys
            .filter { !requiredSet.contains($0) }
            .sorted()
        return required + optional
    }

    /// Pulls the `required` array out of a JSON-Schema object value.
    ///
    /// Only honours the declared ordering in the schema — no alphabetising
    /// — so users who care about argument order in the prompt can pin it
    /// at the schema level.
    private static func extractRequiredArgumentNames(
        from parameters: JSONSchemaValue
    ) -> [String] {
        guard case .object(let fields) = parameters,
              case .array(let requiredArr) = fields["required"] else {
            return []
        }
        return requiredArr.compactMap { value in
            if case .string(let name) = value { return name }
            return nil
        }
    }
}
